# .github/workflows/ci.yml
name: Test Charts

on:
  push:
    branches:
      - master
      - pipeline
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Node dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Generate Charts
        run: npm run generate-charts
      - name: Run E2E Tests
        run: npm run e2e-test
      - name: Get matplotlib source code for unit testing
        run: pip install matplotlib --target=matplotlib
      - name: Run unit tests
        run: python run_unit_test.py      
      - name: Prepare combined report folder
        run: |          
          mkdir combined_report
          cp -r e2e_report combined_report/e2e_report
          cp -r unit_test_report combined_report/unit_test_report
          cp -r unit_test_report/cov combined_report/unit_test_report/cov
          rm -f combined_report/unit_test_report/cov/.gitignore

      - name: Deploy Playwright report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Deploy to GitHub Pages branch
          folder: combined_report
          clean: true # Clean the folder before deploying
